# for local development
services:
  surf-me:
    image: dscribe/basic-node
    build:
      context: .
      target: base
    volumes:
      - .:/app
    user: "root"
    tty: true
    stdin_open: true
