# for local development
version: "3.7"
services:
  surf-me:
    image: dscribe/surf-me
    build:
      context: .
      target: "develop-stage"
    volumes:
      - ".:/app"
    user: 1000:1000
    tty: true
    stdin_open: true
